# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: egorb2302.pathmemo
PackageVersion: 0.2.3
MinimumOSVersion: 10.0.17763.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: pathmemo.exe
  PortableCommandAlias: pathmemo
Commands:
- pathmemo
ReleaseDate: 2026-10-01
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/egorb2302/pathmemo/releases/download/v0.2.3/pathmemo-0.2.3-win-x64.zip
  InstallerSha256: BBB65A7192EA8AFD2AEE765CB39918AD8892AEF6C1C9D9B002E6372EF2B5EABC
- Architecture: arm64
  InstallerUrl: https://github.com/egorb2302/pathmemo/releases/download/v0.2.3/pathmemo-0.2.3-win-arm64.zip
  InstallerSha256: 1545E6FA37915B7AC0C92481D9625835E4B10445DD2481175902DB67419F7FCF
ManifestType: installer
ManifestVersion: 1.10.0
